[package]
name = "cancel-safe-futures"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Alternative futures adapters that are safe to cancel"

[dependencies]
futures-core = { version = "0.3.28", default-features = false }
futures-sink = { version = "0.3.28", default-features = false }
futures-util = { version = "0.3.28", default-features = false, features = ["sink"] }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["rt", "macros", "time"] }
