# adapted from https://github.com/taiki-e/cargo-hack/blob/main/.github/workflows/release.yml

name: Publish release
on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    if: github.repository_owner == 'oxidecomputer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - uses: taiki-e/create-gh-release-action@8df4de6534ceacdaed10a08f73418ca751f31793 # v1
        with:
          changelog: CHANGELOG.md
          title: cancel-safe-futures $version
          branch: main
          prefix: cancel-safe-futures
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
